services:
  redis:
    build: ./Redis
    ports:
      - "6378:6379"
    networks:
      - infra

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - infra

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - redis
    networks:
      - infra

#  order-service:
#    build: ./Order-Service
#    ports:
#      - "8081:8081"
#      - "9090:9090"
#    depends_on:
#      - redis
#      - broker
#    networks:
#      - infra
#
  product-service:
      build: ./product-service
      ports:
        - "8082:8082"
        - "9091:9091"
      depends_on:
        - redis
        - broker
      networks:
        - infra

networks:
  infra:

